query Projects($orderBy: Project_orderBy, $orderDirection: OrderDirection) {
  projects(orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    name
    imageUrl
    description
    createdAt
    owner {
      id
    }
  }
}
