query Project($id: ID!) {
  project(id: $id) {
    name
    imageUrl
    subtitle
    description
    createdAt
    upvotes
    downvotes
    owner {
      id
    }
    votes {
      user {
        id
      }
      vote
      timestamp
    }
  }
}
