name: Build, Test and Release

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Test, Lint and Typecheck
        run: pnpm ci
        env:
          CI: true
          INFURA_KEY: 'empty'
