name: Build, Test and Release

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Codegen
        run: pnpm codegen
      - name: Build
        run: pnpm build
      - name: Test, Lint and Typecheck
        run: pnpm ci
        env:
          CI: true
          INFURA_KEY: 'empty'
      - name: Export Next.js build
        run: cd ui && pnpm next export
      - name: Deploy to GitHub Actions
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/out
